In [ ]:
import gensim
import torch

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import numpy as np

In [ ]:
!pip install annoy

Collecting annoy
  Downloading annoy-1.17.3.tar.gz (647 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 647.5/647.5 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: annoy
  Building wheel for annoy (setup.py) ... done
  Created wheel for annoy: filename=annoy-1.17.3-cp310-cp310-linux_x86_64.whl size=552399 sha256=9db3bae2b638379e4995632172a92c20f1e7eb999f53c58b873312a50f241ef2
  Stored in directory: /root/.cache/pip/wheels/64/8a/da/f714bcf46c5efdcfcac0559e63370c21abe961c48e3992465a
Successfully built annoy
Installing collected packages: annoy
Successfully installed annoy-1.17.3

In [ ]:
from numpy.random import normal
from annoy import AnnoyIndex

In [ ]:
from gensim.scripts.glove2word2vec import glove2word2vec

In [ ]:
from gensim.models import KeyedVectors

# Path to the original GloVe embeddings file
glove_file_path = '/content/drive/MyDrive/glove.6B.50d.txt'

processed_file_path = '/content/Preprocessed.glove'

glove2word2vec(glove_file_path,processed_file_path)

<ipython-input-9-0e5e1ed340fd>:8: DeprecationWarning: Call to deprecated `glove2word2vec` (KeyedVectors.load_word2vec_format(.., binary=False, no_header=True) loads GLoVE text vectors.).
  glove2word2vec(glove_file_path,processed_file_path)

(400001, 50)

In [ ]:
model = KeyedVectors.load_word2vec_format(processed_file_path,binary = False)

In [ ]:
model['word']

array([-0.1643   ,  0.15722  , -0.55021  , -0.3303   ,  0.66463  ,
       -0.1152   , -0.2261   , -0.23674  , -0.86119  ,  0.24319  ,
        0.074499 ,  0.61081  ,  0.73683  , -0.35224  ,  0.61346  ,
        0.0050975, -0.62538  , -0.0050458,  0.18392  , -0.12214  ,
       -0.65973  , -0.30673  ,  0.35038  ,  0.75805  ,  1.0183   ,
       -1.7424   , -1.4277   ,  0.38032  ,  0.37713  , -0.74941  ,
        2.9401   , -0.8097   , -0.66901  ,  0.23123  , -0.073194 ,
       -0.13624  ,  0.24424  , -1.0129   , -0.24919  , -0.06893  ,
        0.70231  , -0.022177 , -0.64684  ,  0.59599  ,  0.027092 ,
        0.11203  ,  0.61214  ,  0.74339  ,  0.23572  , -0.1369   ],
      dtype=float32)

In [ ]:
import random

def get_random_nearest_neighbour(model, noisy_vector):
    # Find the top 5 nearest neighbors to the noisy vector
    nearest_neighbors = model.most_similar(positive=[noisy_vector], topn=5)

    # Generate a random number between 1 and 5 (inclusive)
    random_number = random.randint(1, 5)

    # Use the random number to select a nearest neighbor
    random_nearest_neighbor = nearest_neighbors[random_number - 1]


    return random_nearest_neighbor

In [ ]:
def generate_laplacian_noise_vector(dimension, sensitivity, epsilon):
    rand_vec = normal(size=dimension)
    normalized_vec = rand_vec / np.linalg.norm(rand_vec)
    magnitude = np.random.gamma(shape=dimension, scale=sensitivity / epsilon)
    return normalized_vec * magnitude

In [ ]:
def replace_word(sensitive_word):

    # Generate a noise vector
    noise = generate_laplacian_noise_vector(50, 1.75, 25)
    # Get vector of sensitive word
    original_vec = model[sensitive_word]
    # Get perturbed vector
    noisy_vector = original_vec + noise
    # Get item closest to noisy vector
    privatized_word = get_random_nearest_neighbour(model,noisy_vector)[0]
    # Get word from item

    return privatized_word

In [ ]:
def replace_sentence(sentence, model):
    # Split the sentence into words
    words = sentence.split()
    privatized_sentence = []

    for word in words:
        try:
            # Generate a noise vector
            noise = generate_laplacian_noise_vector(50, 1.5, 25)
            # Get vector of sensitive word
            original_vec = model[word]
            # Get perturbed vector
            noisy_vector = original_vec + noise
            # Get item closest to noisy vector
            privatized_word = get_random_nearest_neighbour(model, noisy_vector)[0]
            # Add the privatized word to the privatized sentence
            privatized_sentence.append(privatized_word)
        except KeyError:
            # If the word is not in the vocabulary, keep it as is
            privatized_sentence.append(word)

    # Join the privatized words to form the privatized sentence
    return ' '.join(privatized_sentence)

In [ ]:
import pandas as pd


df = pd.read_csv('/content/drive/MyDrive/IMDB_Dataset.csv')
df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
import numpy as np
import re
import nltk
from nltk.tokenize import sent_tokenize, word_tokenize

In [ ]:
# Download required NLTK datasets
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...

True

In [ ]:
# Define the list of stopwords and WordNetLemmatizer
stopwords = nltk.corpus.stopwords.words('english')
wn = nltk.WordNetLemmatizer()

In [ ]:
# Define a function to clean the text
def clean_text(text):
    # Remove non-alphabetic characters
    text = re.sub('[^a-zA-Z]', ' ', text)
    # Convert to lowercase
    text = text.lower()
    # Tokenize the text
    text = nltk.word_tokenize(text)
    # Lemmatize the words and remove stopwords
    text = [wn.lemmatize(word) for word in text if word not in stopwords]
    # Join the words back into a string
    text = ' '.join(text)
    return text

In [ ]:
df['review'] = df['review'].apply(clean_text)

In [ ]:
df.head()

                                              review sentiment
0  one reviewer mentioned watching oz episode hoo...  positive
1  wonderful little production br br filming tech...  positive
2  thought wonderful way spend time hot summer we...  positive
3  basically family little boy jake think zombie ...  negative
4  petter mattei love time money visually stunnin...  positive

In [ ]:
embeddings = torch.tensor(model.vectors)


# Move the PyTorch tensor to the GPU
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
embeddings = embeddings.to(device)

In [ ]:
batch_size = 100
total_rows = len(df)
for i in range(0, total_rows, batch_size):
    subset_df = df.iloc[i:i+batch_size]
    subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))
    subset_df.to_csv("/content/privatized_subset_imdb_dataset_{i+1}_{i+batch_size}.csv", index=False)
    print(f"Processed rows {i+1} to {min(i+batch_size, total_rows)}")
    print(subset_df['privatized_text'])

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1 to 100
0     only allmusic mention talk trilogy simpsons su...
1     reminds much produce db bb live-action methods...
2     never something view bringing starting spots a...
3     so lived lot boy trevor ca zombies sofa acquir...
4     solberg mattei ` when cash visual spectacular ...
                            ...
95    martin week stewart dependable actor dying wel...
96    maybe could originally sure than three part co...
97    and most wait too horror b movies cause we fas...
98    worst movies because seen made past probably e...
99    bruno as long wonderful remembered legacy play...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 101 to 200
100    short film inspired would short height feature...
101    okay next night june th cultures exasperation ...
102    bought games perverse sell wal sorry memorable...
103    amusingly awful made movies films shinai blow ...
104    hand afraid early comedy just happening die ma...
                             ...
195    mfecane classes hizzoner ii fantastic kurigalz...
196    ludicrous nystagmus last man vandermark instea...
197    candace grant joyce take go legend “ b movie k...
198    put flexible historical sense film though seem...
199    directed coming sure including lynch scenes so...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 201 to 300
200    interesting cover radio film describes syriana...
201    comedy wwi made veritable canadian producing c...
202    superb tale documentary totally grisly weird s...
203    obviously dream films everything almost felt e...
204    another say warned write entitled application ...
                             ...
295    recent basically misleading print campaigning ...
296    films bleed for sort heatwave currently nation...
297    getting closer newspaper behind studio liked d...
298    way way seven 1/2 fact we hardly splashy left ...
299    street grandson lantern pinewood documentary f...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 301 to 400
300    haraldur sure dismayed should worse film proje...
301    ferritin you physician why fibrinogen we wasti...
302    playful joke smart marvelous flipping tv after...
303    nature film will k chances like who brooke ger...
304    really need come film talent director michel l...
                             ...
395    commented first debuting to shoulder end asses...
396    everything age means ridiculous life like dire...
397    hey babu gwyer films like man rico racer kerou...
398    snowstorm junction blocking intersects patrolm...
399    films otherwise enjoyable sitcom tim law appli...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 401 to 500
400    say fiction black apparently fabulous incredib...
401    surprised movie left feel jipped place physica...
402    comedy ultra pentathlon crunchy constraints fa...
403    focused practical sort really happen 1950s civ...
404    mmorpgs chaired fancy drawn movie come semi-pr...
                             ...
495    british terrible subsequently tied critics mcb...
496    second worry cared author animals farm explain...
497    character extremely boring surprised rest retu...
498    elated films highlights sexual encounter ruine...
499    festive competition originally u miramax bug h...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 501 to 600
500    roof ability 39-point renditions favorite nove...
501    friend legendary directly beloved hollywood da...
502    disappointing producing like sure made days pa...
503    get nice proves series sandoval performance ne...
504    still . favorite films could guidelines know a...
                             ...
595    answer story watched film left emotionally dra...
596    last ago tegan careers boy witnessing group ki...
597    end go watching burt reed playing movies same ...
598    headlines love smith twenty time each unique d...
599    learning parody drama intercut deeply rivieres...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 601 to 700
600    absolutely good hollywood greatest watching ag...
601    birdie awesome film life things well fun movie...
602    anybody talk middle putting technologies telev...
603    worse all-in-one come making well maybe little...
604    weird 1090 should one foremost outrageous euro...
                             ...
695    ok foolish blame giving came terrible film yea...
696    talking became may voice scary what else ts br...
697    when released better humility ouagadougou holl...
698    starting fluff without br bb crazy done talent...
699    decided tonight film turned katherine hasmonea...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 701 to 800
700    doubt headlights review nothing hopefully dram...
701    enjoying wondering and acting film more additi...
702    scenario concerned abound a . associate james ...
703    shinnō ews cannot unwilling expectations sure ...
704    happy mostly america small towns whenever norm...
                             ...
795    lorna green janine humorist presentation artis...
796    starter knotts included come easy buddy almost...
797    julia disfigured flawed documentary developed ...
798    sex go top what det br what sister chaplin 200...
799    loved divine provided what story story populat...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 801 to 900
800    do things think why siege multiple notion blu-...
801    comedy pathos start finishing c + painting new...
802    history tv 50 freshness innovation usual whip ...
803    get do everything convey granny ninth sister a...
804    answer reflected guidelines show web quite sad...
                             ...
895    messed hilarious none decline peculiar osama s...
896    either four playing movie half now filmed brin...
897    managers why a boston world films cannes febru...
898    else would br regio expect colleagues robb pro...
899    increases script amount portrayed project favo...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 901 to 1000
900    nice cinema ahead again cn gt thing nineteen w...
901    out professionally match pension trouble seaso...
902    well demurral hollywood looking seen br bb act...
903    ground moine ews locomotives illegally johnny ...
904    `` own movie tragedy delightfully hackneyed do...
                             ...
995    really sacred give goosen fosselius days 'm vi...
996    disillusioned hate loving convinced overwrough...
997    sometimes pull playing substantive applaud dra...
998    unlike go wo directed experience model mind cr...
999    like microbiology essay however depicts animal...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1001 to 1100
1000    movies horrendous rather bothered write review...
1001    animated corp. familiar 'll writer work necess...
1002    believed praising movies hearsay thinking movi...
1003    film something used location made terrific sho...
1004    curiously so film so both lot image norway wai...
                              ...
1095    immoral reprehensible simple rubbish shared wh...
1096    wake comedy ever seeing first indeed way littl...
1097    uttered rip quatermass disquisitiones third mi...
1098    biography space sz ts yu cattermole hill publi...
1099    idea behind film greatest describes always wom...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1101 to 1200
1100    celebrities locomotives gr not marvelous only ...
1101    cares faith suddenly waited films sure followi...
1102    fourth 'll start say films sounded intriguing ...
1103    billy rings foster biography partners films su...
1104    took fear ability alexander shelley now one br...
                              ...
1195    likewise doubtful quality chronicling content ...
1196    attempting reconciling some nothing issue movi...
1197    response fenders spoiler connector db ts wrote...
1198    greatest comedy fantastic nominated kenen c.j....
1199    mayan she keeping interest quest besides just ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1201 to 1300
1200    bad films same fun little same either folks bl...
1201    excellent movies wishes take all cd others pur...
1202    comedy simply money time funds year special ox...
1203    balance hand wants completely wordy only makin...
1204    began interesting morally something little jud...
                              ...
1295    woman remarks ] splash cocoon rimsza made o co...
1296    seemed anyone allow movies keselowski roach re...
1297    documentary another australian could quickly d...
1298    keeping lillian jossa cause offer video howeve...
1299    took days monster almost boring do least howev...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1301 to 1400
1300    really much you those is people used night bec...
1301    like twisty united lane tough picking will vie...
1302    12 way and still unconvincing enthralling much...
1303    named comedy haired woman needed get roots col...
1304    one best movie but popular hollywood good dire...
                              ...
1395    loved think grisly disgusting why tore animal ...
1396    servant barrett mobster in ii urville kevin ez...
1397    'cause entire three where documentary would le...
1398    a whahng retelling numeral ō wonderful wuxie m...
1399    dreams shows action crowded trek dream sordid ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1401 to 1500
1400    came movie speak jennifer magorian books enjoy...
1401    scaring films carry calling resonates hours he...
1402    road perdition trepidation peter cooper score ...
1403    well `` movie best performances kenneth day br...
1404    buy some come every seagall movies first ones ...
                              ...
1495    film bad future indeed katie worked unfailing ...
1496    good concern animated humorous and worth renta...
1497    time easy year movie some fun films way godzil...
1498    the james ford melodically caught fictional os...
1499    coming film colors film whether know fannn fav...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1501 to 1600
1500    yeah sorry divine dreadful obviously movie com...
1501    everyone little acting one thing honor gone wr...
1502    think several film concerned comedy , acclaime...
1503    same luck fifth produce movies nzr db written ...
1504    but over hardrada so cornwall well particularl...
                              ...
1595    deferential charles condoleezza sadness wherev...
1596    boring brilliant pieces following inefficiency...
1597    two fellow directed dating left suffering set ...
1598    feel turner m&c severe 1949 musical time once ...
1599    imitation swedish film mood popular blinkende ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1601 to 1700
1600    fifth one worst piece creating straight networ...
1601    beforehand identification find someone keep ac...
1602    terrible film 've far action reasons well imag...
1603    quality writing worst cast electronics unemplo...
1604    contained led armrests win if it care book run...
                              ...
1695    reviewing group literature translation origina...
1696    brought hoped french . contentious missions di...
1697    despite according network channel comedy as no...
1698    reichenstein o'brien ford due dubious other ko...
1699    awful starring aftermath the recording guitar ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1701 to 1800
1700    movies double after lacked casting intuitive a...
1701    films suffering fact 20 movies corroborate pro...
1702    premise suck adding fourth may walker lynch th...
1703    sure develop suspenseful frequently feature-le...
1704    tag trooper source featured team dread disappo...
                              ...
1795    funny films really whenever entertains only ev...
1796    ask writer consultant william gove loan search...
1797    give films four superstar aakash beautiful cin...
1798    chuckle burlesque scream records star famed ny...
1799    me guys why film could nothing great afraid sh...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1801 to 1900
1800    musically speaking traurig prague saved fisher...
1801    never adeus those give coming editing movies d...
1802    seems seemed those just go nothing european in...
1803    evangelical subversive getting fears mongering...
1804    audio recovered referring lancome roller espec...
                              ...
1895    allocated likes winner will semifinal shooting...
1896    movies provide something anybody hopeful high ...
1897    corazon place most interesting experiment gues...
1898    too dislike demanded response comment practica...
1899    seeing rather wait for mediocre thin component...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 1901 to 2000
1900    amazing melodrama drama drama italian husband ...
1901    grille grille releasing regarded seem risque w...
1902    interesting movies jordana ladd young woman fl...
1903    seen films late local broadcast location think...
1904    lame victim do watching film commercial critic...
                              ...
1995    really milwaukee co-produced hoffman baigelman...
1996    insulin rating br ews cells like bowfinger sho...
1997    comedy already included j g several celebs pro...
1998    afraid films to break throwing watch everyone ...
1999    worse movies never recent rogers verde-type th...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2001 to 2100
2000    fishermen entire perjuangan p disc good broadc...
2001    grandfather convicted husband inmates sharlene...
2002    wonder play league thought comedy brings secti...
2003    hbo network drama screen playmakers audience k...
2004    movies did 'll see giant fan adults live-actio...
                              ...
2095    kidding i write statement viewer trashing film...
2096    and things even anyway things liked movie leng...
2097    ' things sequel not come but good almost extre...
2098    watching remake trying request main one docume...
2099    more come trees nolan nevertheless make profes...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2101 to 2200
2100    all performer automatically surprised comedy s...
2101    so giving another player commission computers ...
2102    mix feel le valseuses translated actor aristid...
2103    fame baywatch indiana moore strategy general u...
2104    acquired movie truck boot sales expecting fict...
                              ...
2195    in ready more non-denominational simply mormon...
2196    number only thing humanity over teaching exper...
2197    nepal burials place seven word very anyway rea...
2198    well decade called kitschy nazi directed joe j...
2199    everybody big mcginniss much realize 1.2 just ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2201 to 2300
2200    again out radiate week days television because...
2201    comedy titles melon o.g. ews complete review t...
2202    same before films require night last days obvi...
2203    crime one teenage movie graduate smiled turn d...
2204    remember movie typical get searching kept part...
                              ...
2295    getting production seen better instrumental bb...
2296    whose punk n get films matter evolved close mo...
2297    attending braxiatel art divert pay kansas cana...
2298    mind more however drama words comment stroman ...
2299    bugar lugosi too game the considered really lu...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2301 to 2400
2300    higher spending likely excuse rising deputy ta...
2301    sweet film seeing china another workaholic eas...
2302    most easy think some underneath renny unfounde...
2303    shanghai eye ask next 27-year japan woman begi...
2304    heard `` welled films fifty going unfortunatel...
                              ...
2395    naruto translates spiral arrival within new de...
2396    eucalyptus creature shows happens happen prais...
2397    heard enjoying stuart loeb damned ii read outr...
2398    tim lewis bullying acholoic drug addicted cowa...
2399    admit woody cartoon number london film festiva...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2401 to 2500
2400    but lines taiex what go gr br 'd you comedy qu...
2401    bothering honestly wants anyone unusually well...
2402    something imagine incongruous rituals lively c...
2403    sit everyone comedy son higher depends discern...
2404    sure movie category accurately three print scr...
                              ...
2495    came success movies ecuador gavras important p...
2496    even relevant utterly particular book brad kra...
2497    looks inward britain airbus crew henry richard...
2498    films breech money toward humorous outrageousn...
2499    carnaval terrine no chinese offers wonderful d...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2501 to 2600
2500    might really feeling piling boiling dung going...
2501    weekend shoot sailors sidewalk bus tyrannical ...
2502    seen one film eaten symptoms another frankly b...
2503    g we hardcore softcore stay films antidote som...
2504    neither strange move promote films — good deal...
                              ...
2595    glad extended satisfied now greatest dictator ...
2596    unbelievable philosophical deep genius masterp...
2597    well yet movie play weakness come stiff oppose...
2598    borat shirl she deep sexual problem starting f...
2599    henry corbett although instant things success ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2601 to 2700
2600    similarly huge seagal star last coming film ma...
2601    doctors films there votes adding come somethin...
2602    cutlet works what conversation like movies som...
2603    when wcau running fantasy superboy my mornings...
2604    adult-oriented another estyle.com ulsterman fi...
                              ...
2695    eighth collaborations angell dietrich consulta...
2696    great film u shown jurassic hall chaotic theor...
2697    comedy recapture realm increasingly badaga ame...
2698    game reveals broadway now father tenants movie...
2699    nightmare movie something glenn rena spot aa s...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2701 to 2800
2700    samurai ii really bit decide ape third the chr...
2701    stupid films starting flavored pornography fla...
2702    insult tell indeed why 've sequel cinematic ni...
2703    lazily drama theatrical we giving drama movie ...
2704    great movie ever kind meaning tackles describe...
                              ...
2795    fonda villain good robinson benefits vicious l...
2796    bat than delighted resident neilsen spot just ...
2797    best discover islands brought made turn drama ...
2798    purpose drama me tale movies focus own green s...
2799    movies sparking saw screener coupla week years...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2801 to 2900
2800    anyone watching movies agree starred films sch...
2801    look somebody and adventure types videos games...
2802    certainly indeed many documentary removed subj...
2803    only strange idea particularly idea schmaltz m...
2804    chairman ludwig stroheim second aimed entirely...
                              ...
2895    suited shows sequel ajeel newsprint novels mor...
2896    immortal bad rottweiler tease ali g too cost l...
2897    rarely comment films 1992 movies bulk business...
2898    interesting movie based three georges feuillad...
2899    went details dvds box terrible black princess ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 2901 to 3000
2900    starts pretty indonesian preferably water back...
2901    during fourth third screen again months abstai...
2902    why film swindled everything than college must...
2903    sect movie same truly russian freedom you impr...
2904    . film jeskid awesome check comforted : alice ...
                              ...
2995    knowledge head doing needs know xenosaga filmi...
2996    fans carol lillie arsenio minnelli genes moore...
2997    resign nathan lighter incense disused excellen...
2998    corriere scott lee basinger above classes scho...
2999    worked film bounce cry tomorrow make go aghast...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3001 to 3100
3000    purchased full soundtrack chuck local nacra ma...
3001    already tried equivalent likely movie possibil...
3002    know asriel author arguably success first thea...
3003    swedish producers beast thriller did why morti...
3004    day titles fiction likely devil half evening d...
                              ...
3095    too dysfunctional film whose hands horrible di...
3096    same movie airplane satellite attacked space p...
3097    balancing terrorism once whose winning player ...
3098    surprised film fifth rest trying remarkable su...
3099    hacking remembers indeed idea two star — as ro...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3101 to 3200
3100    even comedy year still remembered hard drove s...
3101    sunday loans curiosity essay watched of time s...
3102    dodig soderbergh everyone vibiana bored plotti...
3103    know leaving viewers movies wished blast eat g...
3104    enormous expectation movie rent audio store bo...
                              ...
3195    danger attempt seen develop eroticism two yory...
3196    july russian communist months sailor boat russ...
3197    still film made people nobody reason already r...
3198    came combination impressive natalie ann miller...
3199    breakthrough expired hate it necessary fable c...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3201 to 3300
3200    really cesar noten dalen comedy dogtown is fil...
3201    enough gays themed movie might saw films exact...
3202    past title soon imply pig peppa star fatso rab...
3203    others say fast film little mean different ree...
3204    another folk camberg gonna films based old rad...
                              ...
3295    qualifying time year everything beijing dying ...
3296    brosnan climbs boat moore lovably bus theatric...
3297    previous nrk silver cliches next lot really co...
3298    movies firm those flu formidable goes while h5...
3299    seen film saw keeping doubt make making knows ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3301 to 3400
3300    kind someone get goal unfortunately hollywood ...
3301    legendary britain movie worse given back free ...
3302    refer patricia ross captivating b drama john h...
3303    profits protein wayne vincent damphousse negot...
3304    man line trailers acclaimed meyers characteriz...
                              ...
3395    rider lineage first already western davis made...
3396    answer 're assessment tbs overdrawn other too ...
3397    wmd normally low rather appearing proliferatin...
3398    making thriller movie what maintain gangster d...
3399    murderer call surprisingly flirting superhero ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3401 to 3500
3400    in level chocolate fares j hollywood dong ho m...
3401    five stories written richard balthasar several...
3402    both while films set throughout communist yugo...
3403    maslin remarked film draw plots percolate char...
3404    sixth saw movies tv though eight ago father ne...
                              ...
3495    brought hollywood strongest roll positive revi...
3496    film shortest assaulted agonize ends comedy co...
3497    going movies a usual going another money early...
3498    work george luck life shows however watched se...
3499    impressive documentaries authorization prosper...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3501 to 3600
3500    movie writer mann boelcke obviously impression...
3501    believe read quick casualties have lose movie ...
3502    bad comedy loves watch second time an obviousl...
3503    moonwalker be drama alert williams harrison ni...
3504    sci hd great loved good starting only bartok k...
                              ...
3595    knew coming dreadful shocking one boring movie...
3596    three much comedy playing nancy charlton play ...
3597    since darren quants after thriller documentary...
3598    beneath sterile tree friskiness computer photo...
3599    one indeed richards hamlet divine sad siren ac...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3601 to 3700
3600    mercifully shows wannabe northern staying aflo...
3601    difficult foolish attempting altman class myst...
3602    shit dear bring latest somerset hiberno-englis...
3603    hollywood possible devastating film ever see i...
3604    torain weiss announcer consider see cameron pe...
                              ...
3695    many people maybe carey patient say say cn emd...
3696    movie sure trouble rest given islam showing my...
3697    good prequel guilty large where a paying witne...
3698    amazing movie _ networkers peletier existence ...
3699    probably film our seen turn dismissed dad drea...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3701 to 3800
3700    ea showing ta must classics fbi we feel set il...
3701    calonge akelly these episode zealand horror aw...
3702    jaane pretty for approval will picked decade m...
3703    film enlightening fun lacking movies actor clu...
3704    mom film still last however deaths he four dad...
                              ...
3795    days leonard vernon tends sardonic prior cussi...
3796    made to now devastating films ever atleast hap...
3797    opportunity look theatrical losing turning loo...
3798    mee qué proved k 0530 pa chasseur br br both s...
3799    big find directed island already pervasive myt...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3801 to 3900
3800    rapper author movies inc. came difficulty poem...
3801    talking metro-north ’s desire both screenplay ...
3802    made-for-tv as ? tale obviously takes see actu...
3803    book triumphant prince intriguing american des...
3804    those say hard point tv remake arguing vast su...
                              ...
3895    devastating horror movie even wittiest films b...
3896    her dewaere series noirs tremendous detests en...
3897    past films third compilation constantly experi...
3898    comedy delivers set amiable teenager neighbour...
3899    reading announcement came films excellent film...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 3901 to 4000
3900    drama original tale train working good part ha...
3901    gets representing blend acts funny seeing thea...
3902    brainchild animated settlements american tony ...
3903    readily serious elvis vehicles ever to bring u...
3904    always still set highlight badminton puppetry ...
                              ...
3995    starting backgrounder paparazzo princess milpa...
3996    pulled dad bite butt campy not still guess cox...
3997    film promised bats there adding knows just har...
3998    came directed are time all going pleased guilt...
3999    loved kolchak tonight stalker ago took place p...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4001 to 4100
4000    feel slovak reworked abducted shore story thin...
4001    dee somebody like anchored florida yellow cont...
4002    midnight when making flicks films interesting ...
4003    courageous attempt bring couple shapes book es...
4004    flubber iii demiurge arguing strong else playw...
                              ...
4095    opinions directed multimedia displays role min...
4096    gosh divine get gone look like fun good thrill...
4097    watch animated following start happened catche...
4098    other gifted 60 charismatic starred rain hooey...
4099    . what disastrous films best saw say meant ver...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4101 to 4200
4100    evangelical everybody film horrible coupé mk n...
4101    user seen therapies move willing quoted volley...
4102    judges group film to committee give stages mus...
4103    movie go assistant andrew williams even welcom...
4104    because parents one aftermath hollywood often ...
                              ...
4195    pity dreadful regret podium setting lamp light...
4196    film victim pessimism modern men herself love ...
4197    started go apprentice year days you ? obviousl...
4198    seeing film guys smith squarepants conservativ...
4199    panic manipulative everyone gemstones comic su...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4201 to 4300
4200    movies 're remembered who maked snow manor rea...
4201    now things putting spoil political sequel diff...
4202    comedy occasion film looks finally hollywood d...
4203    looks description conditions ne finds are some...
4204    really accent typically friend buried yamaguch...
                              ...
4295    refrain low school portuguese illicit quite da...
4296    call sunday school `` could generous indeed ev...
4297    first want cause rare need start suggestion br...
4298    again movie time came wonder following investi...
4299    as anachronism refer shows mostly take point n...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4301 to 4400
4300    cliched many attributed film , typically super...
4301    same shallowest show plots thinking seem _ ......
4302    he loud movies went blu-ray much movies nice c...
4303    originally can in massive tale last decoration...
4304    donald toms have 'm movies shrugged certain su...
                              ...
4395    get start somewhere movie like attempt icy nob...
4396    say gigantic known runs indeed people fun wond...
4397    whom movies always aired wednesday 'll summer ...
4398    titles getting even true n't doors films short...
4399    because sleep weeks into movie mtv went movie ...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4401 to 4500
4400    film role optimism moving competence niveau pl...
4401    robinson fit beguiling relationship doctor ban...
4402    ballads mcfly u-shaped whack movies carbonara ...
4403    bother watching film to enough advice well mar...
4404    soccer episcopalian hear little everything mov...
                              ...
4495    forcing watching works because gone would howe...
4496    georgic john pieplow mike gage mary soltren sh...
4497    end go film knowledge going containing histori...
4498    bad feeling saw cheap winning working last par...
4499    badly correctly bleeding things screen blood g...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4501 to 4600
4500    hollywood opera obviously modern back horrifyi...
4501    same back by comedy what looking are because s...
4502    watched really country movie long ` really as ...
4503    fact film dvd guaranteed lacking always fact f...
4504    enormous stars adventures nickname 're field p...
                              ...
4595    sometimes qualification movie pure masterwork ...
4596    hey however contain squeaky feels health price...
4597    'd tension worry clinic medical stuff with get...
4598    looooonnnggg got late thanks comic surviving d...
4599    a better riveting film another john watson gav...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4601 to 4700
4600    nonlethal biblical musical add battle sight ma...
4601    man show when young best rotate owned love fir...
4602    elite pleaded could chief arrested born victim...
4603    similarly like talking lomax chester films par...
4604    spader flynn this tara hood northern insurgenc...
                              ...
4695    comedy moving optimistic very whether ! acted ...
4696    small sailing own walk woman movie aisle rent ...
4697    cannot going rome standing provided order bish...
4698    bischoff mehta historically some excellent pok...
4699    deathstalker film graham anderson actor rick h...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4701 to 4800
4700    considerably supremely white films galleries f...
4701    nrbq wind stones released inspiration where en...
4702    feeling staggeringly awesome plotting flatline...
4703    conspiracy documentary contains holes would dr...
4704    tell seeing whose studio came idea start miffe...
                              ...
4795    drawing stress either another outstanding shap...
4796    ride publicly early saw most they started go e...
4797    welcoming heavens insights thinking motivation...
4798    really enjoys film cheesy any schemer vin petr...
4799    decision however film height schaul darks achi...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4801 to 4900
4800    sort squirreled movie something catch call plo...
4801    clever book relationship displayed eight its c...
4802    talent own characterize sequel center newly di...
4803    appreciate help hire identified mind movie fil...
4804    pamlico cruz bette final exhibitions rogers ev...
                              ...
4895    sara frank gerwig greta start ? grandfather br...
4896    camera crucial read translation turkey dreadfu...
4897    films something though comical contrary means ...
4898    need minority reason among father actually com...
4899    strangely little usually slight bulky much res...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 4901 to 5000
4900    attracting films humorous low hold own life st...
4901    being featuring only names watch enough common...
4902    adolescents youth second experiencing tekken w...
4903    or longest calls span sixth film authorities s...
4904    connecting stories a later now screen an popul...
                              ...
4995    intriguing slasher debut similar doctor mk sd ...
4996    barely appearances first coming month woman wa...
4997    jet wang finds orator nato sequel lets film bl...
4998    apartments film verdict tim senate saying real...
4999    maybe urgency think worst deneuve hollywood pe...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 5001 to 5100
5000    films turn ` four friend black starring scenes...
5001    movies type movies pricey being getting bad of...
5002    polygram broadcast box made helped championshi...
5003    bukovina statistically occasionally funny quir...
5004    exactly rated acts comedy noticeably history m...
                              ...
5095    comedy weird watched poisoning drop psilcybe l...
5096    goldie hawn sir buyer films highest only wo su...
5097    caddyshack similarly ambient spooky funny orig...
5098    rents couple movies much granddaughter this la...
5099    brought movies comic main finally movies somet...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 5101 to 5200
5100    quality bros. elektra meant starred milam anth...
5101    seen movies gorgeous flying onecare cinema han...
5102    film portrays rented film intensity horrible c...
5103    documentary proposal playful only near good co...
5104    scintillating fiction small group idealistic m...
                              ...
5195    really horror cheer very dreams porky often sa...
5196    game cutscenes film truthfulness waited one ch...
5197    well movie horrible socialize new screens star...
5198    official hour bleeds awful than as dismal mora...
5199    glencairn picture also movie g f such army uni...
Name: privatized_text, Length: 100, dtype: object

<ipython-input-30-5d1840b45205>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df['privatized_text'] = subset_df['review'].apply(lambda x: replace_sentence(x, model))

Processed rows 5201 to 5300
5200    conflict iraq killed joining soldier flesh inh...
5201    two hollywood especially 've cherish second in...
5202    obviously majestic heartwrenching films ripste...
5203    greatest role ever movie things built do movie...
5204    crazy theme longtime hard-drinking player coin...
                              ...
5295    might perhaps hoping terminator sports thought...
5296    astronaut bob north davey multinucleated comra...
5297    well gone noting only aftermath adaptation bes...
5298    spoiler switchable ramped by put suspense rele...
5299    each believe film thankfully without get disho...
Name: privatized_text, Length: 100, dtype: object